### ISSUE TITLE
Example Data

### ISSUE THREAD

**Issue by jfmiller52** [themattrix/discord-caravan#1]
Do you have an example of the gyms.json file?  Or maybe a discord server where you already have this implemented so i can see how it looks?

**Comment by themattrix** [comment]
Here's an example layout:

```json
{
  "Gym Name 1": {
    "location": "latitude,longitude"
  },
  "Gym Name 2": {
    "location": "latitude,longitude",
    "aliases": [
      "Alias A",
      "Alias B"
    ]
  }
}
```

**Comment by themattrix** [comment]
I've updated the README with an example. I'm going to close this issue, but let me know if you'd like any further clarification!

**Comment by jfmiller52** [comment]
Have you thought about using the format you can scrape from pokemongomap.info?

**Comment by themattrix** [comment]
Do you have any resources on that?

**Comment by jfmiller52** [comment]
Flag Statue | 42.040465 | -88.28871
-- | -- | --
Elgin Windmill | 42.03825 | -88.288223
The Gaming Goat | 42.03286 | -88.3282
Virgin Mary Statue | 41.947737 | -88.210595

**Comment by themattrix** [comment]
That would be a night straightforward conversion. Is there a tool that produces that output from the website?

**Comment by jfmiller52** [comment]
There's a Greasemonkey script that pulls the data from pokemongomap.info
